language: node_js
os:
  - linux
dist: xenial
cache:
  directories:
    - ~/.npm
node_js:
  - "14"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  strategy: git
  edge: true,
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master
